### ISSUE TITLE
Dead kernel in jupyter notebook after installing ArcGIS Pro  2.2

### ISSUE THREAD

**Issue by esturdivant-usgs** [esturdivant-usgs/geomorph-working-files#1]
I tried running the notebook.  The kernel tried to connect (message: "Connecting...") but it doesn't appear to succeed because the next message says the kernel has died and it will attempt to restart. The restart fails, producing this message "The kernel has died, and the automatic restart has failed. It is possible the kernel cannot be restarted. If you are not able to restart the kernel, you will still be able to save the notebook, but running code will no longer work until the notebook is reopened." The log in the console includes "Kernel deleted before session."

```
[W 12:36:07.896 NotebookApp] Notebook geomorph-working-files/extractor_ebf10.ipynb is not trusted
[I 12:36:08.993 NotebookApp] Kernel started: 0bf96c48-69ca-4810-8154-4f5fc159af49
Traceback (most recent call last):
  File "C:\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\ipykernel\connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "C:\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\IPython\__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "C:\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\IPython\terminal\embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "C:\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\IPython\terminal\interactiveshell.py", line 22, in <module>
    from prompt_toolkit.shortcuts import create_prompt_application, create_eventloop, create_prompt_layout, create_output
ImportError: cannot import name 'create_prompt_application'
```

**Comment by esturdivant-usgs** [comment]
This solution worked: https://github.com/jupyter/jupyter_console/issues/158

In arcgispro-py3, `pip install prompt-toolkit==1.0.15`
